language: cpp

compiler:

  - gcc
  - clang

os:
  - linux
  - osx

addons:
  apt:
    sources:
      - ubuntu-precise
    packages:
      - libsdl2-dev



before_script:  
    - mkdir Build
    - cd Build
    - cmake ..

script: make  


