language: cpp

compiler:

  - gcc
  - clang

os:
  - linux
  - osx

install:

  - if [ "$TRAVIS_OS_NAME" == "linux" ];  then sudo add-apt-repository ppa:team-xbmc/ppa -y; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ];  then sudo apt-get update -q; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ];  then sudo apt-get install libsdl2-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ];  then sudo apt-get install pandoc; fi

  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install sdl2; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install pandoc; fi




before_script:  
    - mkdir Build
    - cd Build
    - cmake ..

script: make  


