language: cpp

compiler:

  - gcc
  - clang

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - libsdl2-dev


before_script:  
    - mkdir Build
    - cd Build
    - cmake ..

script: make  


